# Generated by Django 4.0.1 on 2022-01-22 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('symbol', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator('^[A-Z]*$', 'Only uppercase letters allowed.')])),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('From', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrencyFrom', to='api.currency')),
                ('To', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CurrencyTo', to='api.currency')),
            ],
            options={
                'ordering': ['From'],
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='rates',
            field=models.ManyToManyField(through='api.ExchangeRate', to='api.Currency'),
        ),
    ]
